import React, { useState } from 'react';
import { GitHubService } from '../../services/gitHubService';

interface GitHubCreateModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSuccess: (repoUrl: string) => void;
    token: string | null;
    setToken: (token: string) => void;
    files: { path: string; content: string }[];
}

const GitHubCreateModal: React.FC<GitHubCreateModalProps> = ({ isOpen, onClose, onSuccess, token, setToken, files }) => {
    const [repoName, setRepoName] = useState('');
    const [isPrivate, setIsPrivate] = useState(true);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [status, setStatus] = useState<string>('');

    React.useEffect(() => {
        if (isOpen) {
            setError(null);
            setStatus('');
            setIsLoading(false);
        }
    }, [isOpen]);

    if (!isOpen) return null;

    const handleCreate = async () => {
        if (!token) {
            setError("Personal Access Token is required.");
            return;
        }
        if (!repoName) {
            setError("Repository name is required.");
            return;
        }

        setIsLoading(true);
        setError(null);
        setStatus('Initializing GitHub Service...');

        try {
            const gh = new GitHubService(token);

            // 1. Verify Token
            setStatus('Verifying Token...');
            const username = await gh.checkToken();
            console.log(`Verified GitHub user: ${username}`);

            // 2. Create Repo
            setStatus('Creating Repository...');
            const repoData = await gh.createRepository(repoName, isPrivate, "Generated by Agent Starter Pack");
            console.log(`Repository created: ${repoData.html_url}`);

            // 3. Push Files
            setStatus('Pushing Code...');
            // We need to map our flat file list to the structure expected by the service
            // The service expects { path: string, content: string }
            // Our files from generateAgentFiles usually have relative paths
            await gh.pushFilesToRepository(
                username, // owner
                repoData.name, // repo
                repoData.default_branch, // branch
                files
            );

            setStatus('Done!');
            onSuccess(repoData.html_url);
            onClose();

        } catch (err: any) {
            console.error(err);
            setError(err.message || "Failed to create repository.");
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="fixed inset-0 bg-black bg-opacity-70 z-50 flex justify-center items-center p-4">
            <div className="bg-gray-800 rounded-lg shadow-2xl w-full max-w-md border border-gray-700 p-6">
                <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
                    <svg className="w-6 h-6" viewBox="0 0 24 24" fill="currentColor">
                        <path fillRule="evenodd" clipRule="evenodd" d="M12 2C6.477 2 2 6.477 2 12c0 4.42 2.865 8.17 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.604 9.604 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.477 17.522 2 12 2z" />
                    </svg>
                    Push to GitHub
                </h2>

                <div className="space-y-4">
                    {!token ? (
                        <div>
                            <label className="block text-sm font-medium text-gray-400 mb-1">
                                Personal Access Token (PAT)
                            </label>
                            <input
                                type="password"
                                value={token || ''}
                                onChange={(e) => setToken(e.target.value)}
                                className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2 text-white focus:ring-teal-500"
                                placeholder="Token..."
                            />
                            <p className="text-xs text-gray-500 mt-1">Token requires <code>repo</code> scope.</p>
                        </div>
                    ) : (
                        <div className="flex items-center justify-between bg-gray-700/50 p-3 rounded border border-gray-600">
                            <span className="text-sm text-gray-300">Token Set</span>
                            <button
                                onClick={() => setToken('')}
                                className="text-xs text-teal-400 hover:text-teal-300 underline"
                            >
                                Change Token
                            </button>
                        </div>
                    )}

                    <div>
                        <label className="block text-sm font-medium text-gray-400 mb-1">
                            Repository Name
                        </label>
                        <input
                            type="text"
                            value={repoName}
                            onChange={(e) => setRepoName(e.target.value)}
                            className="w-full bg-gray-700 border border-gray-600 rounded px-3 py-2 text-white focus:ring-teal-500"
                            placeholder="my-agent"
                        />
                    </div>

                    <div className="flex items-center gap-2">
                        <input
                            type="checkbox"
                            id="privateRepo"
                            checked={isPrivate}
                            onChange={(e) => setIsPrivate(e.target.checked)}
                            className="bg-gray-700 border-gray-600 rounded text-teal-500 focus:ring-teal-500"
                        />
                        <label htmlFor="privateRepo" className="text-sm text-gray-300">Private Repository</label>
                    </div>

                    {error && (
                        <div className="bg-red-900/50 border border-red-700 text-red-200 text-sm p-3 rounded">
                            {error}
                        </div>
                    )}

                    {status && (
                        <div className="text-teal-400 text-sm font-mono animate-pulse">
                            {'>'} {status}
                        </div>
                    )}
                </div>

                <div className="mt-6 flex justify-end gap-3">
                    <button
                        onClick={onClose}
                        className="px-4 py-2 text-gray-300 hover:text-white"
                        disabled={isLoading}
                    >
                        Cancel
                    </button>
                    <button
                        onClick={handleCreate}
                        disabled={isLoading}
                        className="px-4 py-2 bg-teal-600 text-white font-semibold rounded hover:bg-teal-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                    >
                        {isLoading && (
                            <div className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full"></div>
                        )}
                        {isLoading ? 'Processing...' : 'Create & Push'}
                    </button>
                </div>
            </div>
        </div>
    );
};

export default GitHubCreateModal;
